version: '3.8'

services:
  archijeewsrest:
    build: .
    container_name: archijeewsrest_app
    ports:
      - "8080:8080"   # Tomcat direct si besoin
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    depends_on:
      - archijeewsrest
    ports:
      - "8082:80"  # Nginx expos√© sur 8082
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
